service: app

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-2
  stage: dev
  environment:
    JWT_SECRET: ${env:SECRET_KEY}
    DB_HOST: ${env:COCKROACHDB_HOST}
    DB_USER: ${env:COCKROACHDB_PW}
    DB_USER_PASSWORD: ${env:HASH_KEY}
    NODE_ENV: 'production'
  # iamRoleStatements:
  #   - Effect: 'Allow'
  #     Action:
  #       - 'ec2:CreateNetworkInterface'
  #       - 'ec2:DescribeNetworkInterfaces'
  #       - 'ec2:DetachNetworkInterface'
  #       - 'ec2:DeleteNetworkInterface'
  #       - 'ses:SendEmail'
  #     Resource: '*'

functions:
  api:
    handler: src/api.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{any+}
          method: ANY
    vpc:
      securityGroupIds:
        - sg-0bcfb09563828dd83
      subnetIds:
        - subnet-2de2bb61
        - subnet-3414b24f
        - subnet-986693f3
